python train_diffusion_fake_ood_supcon.py \
    --expriment_name 'I2Tdiffusion_OOD_cifar100'\
    --model 'resnet18'\
    --dataset 'cifar100'\
    --size 32\
    --method 'I2Tdiffusion_OOD_DiffusionFake'\
    --print_freq 300\
    --save_freq 100\
    --batch_size 512\
    --num_workers 16\
    --epochs 200\
    --learning_rate 0.05\
    --lr_decay_epochs '100,150'